name: Nutanix VM Actions

on:
  workflow_dispatch:
    inputs:
      s1:
        description: '1: Site Name'
        required: true
        type: choice
        options:
          - Banglore
          - Chennai
          - None
      v1:
        description: '1: VM Name'
        required: true
        type: string
      a1:
        description: '1: Action'
        required: true
        type: choice
        options:
          - start
          - stop
          - restart
      d1:
        description: '1: Delay (min)'
        default: '0'
        type: string

jobs:
  run-batch:
    runs-on: self-hosted # లేదా windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run VM Actions
        shell: powershell
        env:
          NUTANIX_PASS: ${{ secrets.NUTANIX_PASS }}
          NUTANIX_USER: ${{ secrets.NUTANIX_USER }}
        run: |
          $json = @{
            v1 = "${{ github.event.inputs.v1 }}"
            s1 = "${{ github.event.inputs.s1 }}"
            a1 = "${{ github.event.inputs.a1 }}"
            d1 = "${{ github.event.inputs.d1 }}"
          } | ConvertTo-Json -Compress
          .\Scripts\vmrestart-new.ps1 -JsonInputs $json
