- name: Add or Extend Disk
  shell: powershell
  env:
    PE_USERNAME: ${{ secrets.PE_USERNAME }}
    PE_PASSWORD: ${{ secrets.PE_PASSWORD }}
  run: |
    & "$env:GITHUB_WORKSPACE\Scripts\diskprovisioning.ps1" `
      -pe_ip "${{ inputs.pe_ip }}" `
      -vmname "${{ inputs.vmname }}" `
      -disk_action "${{ inputs.disk_action }}" `
      -SizeGB "${{ inputs.SizeGB }}" `
      -DiskAddr "${{ inputs.DiskAddr }}"
