name: Nutanix Snapshot Cmdlet Ops

on:
  workflow_dispatch:
    inputs:
      prism_ip: { description: 'Prism IP', required: true }
      vm_name: { description: 'VM Name', required: true }
      op: { description: 'Op (1:Create, 2:Delete, 3:Restore)', required: true, options: ['1', '2', '3'] }
      snap_name: { description: 'Snapshot Name', required: true }

jobs:
  nutanix-cmdlet-job:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      
      - name: Execute Snapshot Cmdlets
        shell: powershell
        env:
          PE_PASS: ${{ secrets.PE_Password }}
        run: |
          # Use your established path
          & "$env:GITHUB_WORKSPACE\Scripts\Nutanix VM Snapshot.ps1" `
            -PrismIP "${{ github.event.inputs.prism_ip }}" `
            -Username "${{ secrets.PE_Username }}" `
            -Password $env:PE_PASS `
            -VMName "${{ github.event.inputs.vm_name }}" `
            -Operation "${{ github.event.inputs.op }}" `
            -SnapshotName "${{ github.event.inputs.snap_name }}"

          
